# Experimentation Env for my project


## Data

In [2]:
import numpy as np
import sys

def generate_snapshot(mid_price):
    rand = np.random.default_rng()
    res_vec = []

    for i in range(0,3):
        c_speed = rand.uniform(0, 0.3)
        price = rand.integers(0,mid_price)
        quantity = rand.integers(0,mid_price*2)
        res_vec.append([price,quantity,c_speed])

    for i in range(3,6):
        c_speed = rand.uniform(0, 0.3)
        price = rand.integers(mid_price,mid_price*2)
        quantity = rand.integers(0,mid_price*2)
        res_vec.append([-price,quantity,c_speed])

    res_vec = np.vstack(res_vec)

    return res_vec

generate_snapshot(1000)


array([[ 6.37000000e+02,  1.02600000e+03,  2.83428069e-01],
       [ 3.60000000e+01,  1.02800000e+03,  5.64727391e-02],
       [ 1.70000000e+01,  3.62000000e+02,  2.65618105e-01],
       [-1.43800000e+03,  1.37300000e+03,  2.98782983e-01],
       [-1.60300000e+03,  1.78100000e+03,  9.83597690e-02],
       [-1.80600000e+03,  6.50000000e+02,  2.65808154e-01]])

In [3]:
def generate_window():

    res = []
    for i in range(0,100):
        vec = generate_snapshot(1000)
        res.append(vec)

    res = np.stack(res)

    return res

np.shape(generate_window())
        

(100, 6, 3)

In [4]:
def generate_spoof_snapshot(mid_price):
    rand = np.random.default_rng()
    vec = []
    for i in range(0,3):
        c_speed = rand.uniform(0.7, 1)
        price = rand.integers(0,mid_price)
        quantity = rand.integers(mid_price*1.5,mid_price*2)
        vec.append([price,quantity,c_speed])

    for i in range(3,6):
        c_speed = rand.uniform(0, 0.3)
        price = rand.integers(mid_price,mid_price*2)
        quantity = rand.integers(0,mid_price*2)
        vec.append([-price,quantity,c_speed])

    vec = np.vstack(vec)
    return vec


def generate_spoof_window(mid_price):

    res = []
    for i in range(0,100):
        
        if(i > 40 and i<60):
            vec = generate_spoof_snapshot(mid_price)
            res.append(vec)
            
        else:
            vec = generate_snapshot(mid_price)
            res.append(vec)

    res = np.stack(res)
            
    return res

generate_spoof_window(1000)

array([[[ 2.36000000e+02,  1.08300000e+03,  2.36644461e-02],
        [ 2.82000000e+02,  1.70000000e+01,  9.85686488e-02],
        [ 9.78000000e+02,  1.55500000e+03,  5.76280320e-02],
        [-1.31000000e+03,  1.34300000e+03,  2.77140841e-01],
        [-1.83700000e+03,  3.72000000e+02,  1.51773094e-01],
        [-1.99400000e+03,  1.10900000e+03,  3.31869589e-02]],

       [[ 1.02000000e+02,  1.35800000e+03,  2.87176938e-01],
        [ 4.69000000e+02,  1.09300000e+03,  1.35625593e-01],
        [ 5.60000000e+02,  1.55500000e+03,  7.18988068e-02],
        [-1.56700000e+03,  1.12300000e+03,  1.70430593e-01],
        [-1.31600000e+03,  1.50900000e+03,  6.67236843e-02],
        [-1.71800000e+03,  1.42100000e+03,  3.63127132e-02]],

       [[ 3.32000000e+02,  6.00000000e+02,  3.53791176e-02],
        [ 5.54000000e+02,  1.48000000e+03,  5.73928589e-02],
        [ 5.26000000e+02,  5.79000000e+02,  1.77565368e-01],
        [-1.85100000e+03,  1.71700000e+03,  2.85822128e-01],
        [-1.25300000

In [5]:
def generate_data(mid,n):
    vec = []
    half = n//2

    for i in range(0,half):
        vec.append(generate_window())

    for i in range(0,half):
        vec.append(generate_spoof_window(1000))

    vec = np.stack(vec)

    y = np.array([0]*(n//2) + [1]*(n//2))

    return vec, y
    

In [6]:
generate_data(1000, 100)

(array([[[[ 6.28000000e+02,  5.86000000e+02,  1.27280190e-01],
          [ 4.15000000e+02,  2.16000000e+02,  2.27274202e-01],
          [ 4.05000000e+02,  1.48600000e+03,  1.53516087e-01],
          [-1.46700000e+03,  2.80000000e+02,  2.96117851e-01],
          [-1.69800000e+03,  1.47300000e+03,  1.82325619e-01],
          [-1.95000000e+03,  4.77000000e+02,  2.72911964e-01]],
 
         [[ 7.87000000e+02,  1.63200000e+03,  1.93737532e-01],
          [ 2.40000000e+01,  5.96000000e+02,  2.41165023e-01],
          [ 6.20000000e+02,  2.61000000e+02,  1.59539833e-01],
          [-1.79400000e+03,  4.82000000e+02,  1.29117567e-01],
          [-1.30000000e+03,  6.78000000e+02,  1.47270788e-01],
          [-1.09900000e+03,  8.44000000e+02,  2.99496833e-01]],
 
         [[ 9.32000000e+02,  1.42800000e+03,  1.06476504e-01],
          [ 6.02000000e+02,  1.08800000e+03,  1.12016188e-01],
          [ 8.09000000e+02,  1.83300000e+03,  1.84049758e-01],
          [-1.85300000e+03,  9.40000000e+01,  5.5

In [7]:
X, y = generate_data(1000, 100)

## LSTM Model


In [8]:
import torch
import torch.nn as nn

class Anomaly_Detect(nn.Module):
    def __init__(self):
        super().__init__()
        self.lstm = nn.LSTM(input_size=18, hidden_size=64, num_layers=1, batch_first=True)
        self.linear = nn.Linear(in_features=64, out_features=1)

    def forward(self,x):
        out, _ = self.lstm(x)
        res = self.linear(out[:,-1,:])

        return res
        

model = Anomaly_Detect()
    

In [9]:
x = torch.randn(32, 100, 18)  
print(model(x).shape)          

torch.Size([32, 1])


In [10]:
loss_func = nn.BCEWithLogitsLoss()
optimiser = torch.optim.Adam(model.parameters(), lr=0.001)

steps = 100

for epoch in range(steps):
    optimiser.zero_grad()
    output = model(x)
    output = output.squeeze()
    loss = loss_func(output,y)
    loss.backward()
    optimiser.step()

    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss}")
    

TypeError: 'int' object is not callable