# Experimentation Env for my project


## Data

In [1]:
import numpy as np
import sys

def generate_snapshot(mid_price):
    rand = np.random.default_rng()
    res_vec = []

    for i in range(0,3):
        c_speed = rand.uniform(0, 0.3)
        price = rand.integers(0,mid_price)
        quantity = rand.integers(0,mid_price*2)
        res_vec.append([price,quantity,c_speed])

    for i in range(3,6):
        c_speed = rand.uniform(0, 0.3)
        price = rand.integers(mid_price,mid_price*2)
        quantity = rand.integers(0,mid_price*2)
        res_vec.append([-price,quantity,c_speed])

    res_vec = np.vstack(res_vec)

    return res_vec

generate_snapshot(1000)


array([[ 1.89000000e+02,  4.74000000e+02,  1.97626394e-01],
       [ 9.02000000e+02,  2.58000000e+02,  5.15587524e-02],
       [ 6.61000000e+02,  1.39000000e+03,  2.37819586e-02],
       [-1.46700000e+03,  1.54100000e+03,  5.94852469e-02],
       [-1.84700000e+03,  1.68600000e+03,  2.01047045e-02],
       [-1.19100000e+03,  2.80000000e+01,  1.13266905e-02]])

In [2]:
def generate_window():

    res = []
    for i in range(0,100):
        vec = generate_snapshot(1000)
        res.append(vec)

    res = np.stack(res)

    return res

np.shape(generate_window())
        

(100, 6, 3)

In [3]:
def generate_spoof_snapshot(mid_price):
    randnum = np.random.default_rng()
    vec = []
    for i in range(0,3):
        c_speed = randnum.uniform(0.7, 1)
        price = randnum.integers(0,mid_price)
        quantity = randnum.integers(mid_price*1.5,mid_price*2)
        vec.append([price,quantity,c_speed])

    for i in range(3,6):
        c_speed = randnum.uniform(0, 0.3)
        price = randnum.integers(mid_price,mid_price*2)
        quantity = randnum.integers(0,mid_price*2)
        vec.append([-price,quantity,c_speed])

    vec = np.vstack(vec)
    return vec


def generate_spoof_window(mid_price):

    res = []
    for i in range(0,100):
        
        if(i > 40 and i<60):
            vec = generate_spoof_snapshot(mid_price)
            res.append(vec)
            
        else:
            vec = generate_snapshot(mid_price)
            res.append(vec)

    res = np.stack(res)
            
    return res

generate_spoof_window(1000)

array([[[ 1.70000000e+01,  1.30800000e+03,  5.78354490e-02],
        [ 9.54000000e+02,  1.22000000e+03,  1.01349967e-01],
        [ 5.45000000e+02,  1.91300000e+03,  2.51531066e-01],
        [-1.78000000e+03,  6.35000000e+02,  2.82931441e-01],
        [-1.29400000e+03,  1.30000000e+02,  3.26172926e-02],
        [-1.01900000e+03,  1.14500000e+03,  2.72781822e-01]],

       [[ 6.38000000e+02,  1.76200000e+03,  2.75218945e-01],
        [ 9.86000000e+02,  1.29900000e+03,  9.66807807e-02],
        [ 9.90000000e+01,  9.54000000e+02,  2.97834890e-01],
        [-1.61400000e+03,  3.96000000e+02,  6.67819326e-02],
        [-1.07500000e+03,  1.31300000e+03,  7.59659492e-02],
        [-1.17600000e+03,  5.99000000e+02,  2.46797004e-01]],

       [[ 3.84000000e+02,  2.84000000e+02,  2.19543462e-02],
        [ 5.19000000e+02,  1.53900000e+03,  2.01909127e-01],
        [ 1.23000000e+02,  1.46000000e+03,  6.77443490e-02],
        [-1.55500000e+03,  1.14200000e+03,  5.37507561e-02],
        [-1.36600000

In [4]:
def generate_data(mid,n):
    vec = []
    half = n//2

    for i in range(0,half):
        vec.append(generate_window())

    for i in range(0,half):
        vec.append(generate_spoof_window(1000))

    vec = np.stack(vec)

    y = np.array([0]*(n//2) + [1]*(n//2))

    return vec, y
    

In [5]:
generate_data(1000, 100)

(array([[[[ 1.62000000e+02,  1.71700000e+03,  2.93503110e-01],
          [ 7.66000000e+02,  1.23400000e+03,  1.01605713e-01],
          [ 7.94000000e+02,  8.11000000e+02,  2.41342933e-01],
          [-1.53100000e+03,  4.89000000e+02,  1.01564749e-01],
          [-1.82800000e+03,  9.30000000e+02,  1.75522396e-01],
          [-1.68300000e+03,  7.37000000e+02,  2.40367767e-01]],
 
         [[ 4.10000000e+02,  1.24000000e+02,  1.49593843e-01],
          [ 3.28000000e+02,  1.06700000e+03,  1.01426290e-01],
          [ 4.60000000e+01,  3.21000000e+02,  5.09174874e-02],
          [-1.61400000e+03,  1.55800000e+03,  2.61887948e-01],
          [-1.58900000e+03,  9.59000000e+02,  2.13985240e-01],
          [-1.31200000e+03,  8.56000000e+02,  1.51059951e-01]],
 
         [[ 5.52000000e+02,  1.60600000e+03,  2.72158891e-01],
          [ 1.71000000e+02,  9.53000000e+02,  8.34231736e-02],
          [ 9.42000000e+02,  1.98600000e+03,  1.42995224e-01],
          [-1.15200000e+03,  9.34000000e+02,  1.4

In [6]:
X, y = generate_data(1000, 100)

In [17]:
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32)

X = X.reshape(100, 100, 18)

/var/folders/0k/xbwc2s7n14g6q62lb3pycl900000gn/T/ipykernel_19632/931523626.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X = torch.tensor(X, dtype=torch.float32)
/var/folders/0k/xbwc2s7n14g6q62lb3pycl900000gn/T/ipykernel_19632/931523626.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(y, dtype=torch.float32)


In [41]:
from torch.utils.data import TensorDataset, DataLoader, random_split

dataset = TensorDataset(X,y)

tup = DataLoader(dataset,batch_size=32,shuffle=True)

sizeD = len(dataset)
train_data, test_data = random_split(dataset,[int(sizeD*0.8),int(sizeD*0.2)])

train_data = DataLoader(train_data,batch_size=32,shuffle=True)
test_data = DataLoader(test_data,batch_size=32,shuffle=True)

## LSTM Model


In [18]:
import torch
import torch.nn as nn

class Anomaly_Detect(nn.Module):
    def __init__(self):
        super().__init__()
        self.lstm = nn.LSTM(input_size=18, hidden_size=64, num_layers=1, batch_first=True)
        self.linear = nn.Linear(in_features=64, out_features=1)

    def forward(self,x):
        out, _ = self.lstm(x)
        res = self.linear(out[:,-1,:])

        return res
        

model = Anomaly_Detect()
    

In [44]:
loss_func = nn.BCEWithLogitsLoss()
optimiser = torch.optim.Adam(model.parameters(), lr=0.001)

steps = 100

for epoch in range(steps):
    total_train_loss = 0
    model.train()
    for x_batch, y_batch in train_data:
        optimiser.zero_grad()
        output = model(x_batch).squeeze()
        loss = loss_func(output,y_batch)
        total_train_loss += loss
        loss.backward()
        optimiser.step()

    total_train_loss = total_train_loss/len(train_data)

    #------------------
    
    model.eval()
    total_test_loss = 0
    with torch.no_grad():
        for x_batch, y_batch in test_data:
            output = model(x_batch).squeeze()
            loss = loss_func(output,y_batch)
            total_test_loss += loss

        total_test_loss = total_test_loss/len(test_data)
    
    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Train Loss: {total_train_loss}, Test Loss: {total_test_loss}")
    

Epoch 0, Train Loss: 0.30542829632759094, Test Loss: 0.2677685022354126
Epoch 10, Train Loss: 0.2862270176410675, Test Loss: 0.32586339116096497
Epoch 20, Train Loss: 0.238564133644104, Test Loss: 0.3023471236228943
Epoch 30, Train Loss: 0.26676908135414124, Test Loss: 0.2745421230792999
Epoch 40, Train Loss: 0.21911127865314484, Test Loss: 0.2821471691131592
Epoch 50, Train Loss: 0.21111035346984863, Test Loss: 0.295331746339798
Epoch 60, Train Loss: 0.23651869595050812, Test Loss: 0.2909591794013977
Epoch 70, Train Loss: 0.23330378532409668, Test Loss: 0.2899104654788971
Epoch 80, Train Loss: 0.22455108165740967, Test Loss: 0.28630250692367554
Epoch 90, Train Loss: 0.2052360326051712, Test Loss: 0.2886178493499756


In [20]:
print(output.shape)
print(y.shape)

torch.Size([100])
torch.Size([100])


In [43]:
model.eval()

with torch.no_grad():
    out_data = model(data)

    

Anomaly_Detect(
  (lstm): LSTM(18, 64, batch_first=True)
  (linear): Linear(in_features=64, out_features=1, bias=True)
)