# Experimentation Env for my project


In [8]:
import numpy as np
import sys

def generate_snapshot(mid_price):
    rand = np.random.default_rng()
    res_vec = []

    for i in range(0,3):
        c_speed = rand.uniform(0, 0.3)
        price = rand.integers(0,mid_price)
        quantity = rand.integers(0,mid_price*2)
        res_vec.append([price,quantity,c_speed])

    for i in range(3,6):
        c_speed = rand.uniform(0, 0.3)
        price = rand.integers(mid_price,mid_price*2)
        quantity = rand.integers(0,mid_price*2)
        res_vec.append([-price,quantity,c_speed])

    res_vec = np.vstack(res_vec)

    return res_vec

generate_snapshot(1000)


array([[ 7.86000000e+02,  2.52000000e+02,  2.27974442e-01],
       [ 8.56000000e+02,  3.57000000e+02,  5.32688535e-01],
       [ 7.13000000e+02,  7.29000000e+02,  4.12254630e-01],
       [-1.35000000e+03,  1.00000000e+03,  5.00218457e-01],
       [-1.40000000e+03,  1.69400000e+03,  4.42695457e-01],
       [-1.11700000e+03,  1.21600000e+03,  8.01522253e-01]])

In [9]:
def generate_window():

    res = []
    for i in range(0,100):
        vec = generate_snapshot(1000)
        res.append(vec)

    res = np.stack(res)

    return res

np.shape(generate_window())
        

(100, 6, 3)

In [18]:
def generate_spoof_snapshot(mid_price):
    rand = np.random.default_rng()
    vec = []
    for i in range(0,3):
        c_speed = rand.uniform(0.7, 1)
        price = rand.integers(0,mid_price)
        quantity = rand.integers(mid_price*1.5,mid_price*2)
        vec.append([price,quantity,c_speed])

    for i in range(3,6):
        c_speed = rand.uniform(0, 0.3)
        price = rand.integers(mid_price,mid_price*2)
        quantity = rand.integers(0,mid_price*2)
        vec.append([-price,quantity,c_speed])

    vec = np.vstack(vec)
    return vec


def generate_spoof_window(mid_price):

    res = []
    for i in range(0,100):
        
        if(i > 40 and i<60):
            vec = generate_spoof_snapshot(mid_price)
            res.append(vec)
            
        else:
            vec = generate_snapshot(mid_price)
            res.append(vec)

    res = np.stack(res)
            
    return res

generate_spoof_window(1000)

array([[[ 1.67000000e+02,  4.84000000e+02,  6.03569790e-01],
        [ 8.21000000e+02,  1.82100000e+03,  2.41294411e-01],
        [ 3.56000000e+02,  1.84200000e+03,  9.44739693e-01],
        [-1.36000000e+03,  1.93300000e+03,  3.36879132e-01],
        [-1.61800000e+03,  2.90000000e+01,  9.13022097e-01],
        [-1.06700000e+03,  5.12000000e+02,  7.63979743e-01]],

       [[ 9.49000000e+02,  1.91900000e+03,  4.63269209e-01],
        [ 2.43000000e+02,  8.95000000e+02,  7.94696282e-02],
        [ 1.48000000e+02,  2.29000000e+02,  6.52220797e-01],
        [-1.89500000e+03,  3.89000000e+02,  5.36121752e-01],
        [-1.06400000e+03,  1.71400000e+03,  7.92973867e-02],
        [-1.40800000e+03,  1.36100000e+03,  1.67302779e-01]],

       [[ 8.29000000e+02,  5.50000000e+01,  7.32427752e-01],
        [ 8.67000000e+02,  5.10000000e+01,  4.75007858e-01],
        [ 9.60000000e+01,  1.83600000e+03,  4.05708351e-01],
        [-1.52900000e+03,  9.60000000e+02,  6.80196010e-01],
        [-1.20700000

In [20]:
def generate_data(mid,n):
    vec = []
    half = n//2

    for i in range(0,half):
        vec.append(generate_window())

    for i in range(0,half):
        vec.append(generate_spoof_window(1000))

    vec = np.stack(vec)

    y = np.array([0]*(n//2) + [1]*(n//2))

    return vec, y
    

In [21]:
generate_data(1000, 100)

(array([[[[ 8.63000000e+02,  1.27900000e+03,  7.41348194e-01],
          [ 4.09000000e+02,  1.15900000e+03,  2.56439434e-01],
          [ 1.24000000e+02,  4.90000000e+01,  9.91267761e-01],
          [-1.26700000e+03,  6.49000000e+02,  5.33120435e-01],
          [-1.71900000e+03,  7.60000000e+01,  7.90137993e-01],
          [-1.86400000e+03,  1.76600000e+03,  3.87742429e-01]],
 
         [[ 5.45000000e+02,  8.65000000e+02,  4.38816805e-01],
          [ 4.50000000e+02,  9.89000000e+02,  9.91329240e-01],
          [ 1.54000000e+02,  2.59000000e+02,  4.26759558e-01],
          [-1.56800000e+03,  4.32000000e+02,  8.06792311e-01],
          [-1.66600000e+03,  1.15400000e+03,  1.20456068e-01],
          [-1.36300000e+03,  5.78000000e+02,  7.85448548e-01]],
 
         [[ 9.60000000e+02,  7.50000000e+02,  5.69785766e-01],
          [ 9.73000000e+02,  1.85000000e+02,  1.21976530e-01],
          [ 7.29000000e+02,  1.99200000e+03,  8.41695843e-01],
          [-1.46100000e+03,  5.24000000e+02,  6.4